### ISSUE TITLE
Some stuff like HUD and controls are being inverted.

### ISSUE THREAD

**Issue by anartoast** [Goorakh/MirroredStageVariants#4]
Seeker's entire kit is fine, but, soujorn is being inverted. I'm not sure if it's this mod problem or Dragonyck's, so i'm contacting you first.
Modpack code: 019226c4-6304-0d7f-6cde-a9206a6b97e0

**Comment by Goorakh** [comment]
SeekerTweaks' sojourn changes isn't using the expected method to gather player inputs, so this mod can't flip the left/right inputs so they appear normal when mirrored.
This could technically be fixed on my end, but ideally it shouldn't.

I didn't spot any HUD issues, could you give some more details about that?

**Comment by anartoast** [comment]
The HUD part may be on me actually. I see that sometimes the ammo gathered on HUNK mod gets funky but it's probably just a projection that doesn't face you. Either way thanks for responding, i'll avoid the SeekerTweaks.

**Comment by Goorakh** [comment]
UI that marks a position in the world and/or contains text or images that should be flipped has to be accounted for by the mod, currently it's mostly only vanilla effects, since I haven't figured out a catch-all solution for that.
